image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - npm ci
    - npm install -g typescript
    - tsc
    - echo "Compile complete."

deploy-container:
  image: docker:19.03.12
  stage: deploy
  only:
    refs:
      - master
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/psege/livecam:latest .
    - docker push $CI_REGISTRY/psege/livecam:latest